### ISSUE TITLE
Not able to use SingleSelect option as getting error as this.$editorElm.multipleSelect is not a function

### ISSUE THREAD

**Issue by mvgadagi** [ghiscoding/Angular-Slickgrid#870]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 13.0      | 
| Angular-Slickgrid   | 4.1.0       | 
| TypeScript              | 4.4.2      | 

### Describe the Bug
I am error in the console whenever I do select on a single selection 
### Steps to Reproduce

1) Use Slickgrid with SingleSelection option and with simple collection

### Expected Behavior

There should be no error and onCellChange should be triggered after doing single selection

### Current Behavior

As soon as I click on the Single Select, I am getting the error as

```
core.js:6479 ERROR TypeError: this.$editorElm.multipleSelect is not a function
    at SingleSelectEditor.loadSingleValue (selectEditor.js:355:1)
    at SingleSelectEditor.loadValue (selectEditor.js:333:1)
    at makeActiveCellEditable (slick.grid.js:5145:23)
    at setActiveCellInternal (slick.grid.js:5018:13)
    at gotoCell (slick.grid.js:5824:7)
    at HTMLDivElement.handleDblClick (slick.grid.js:4739:9)
    at HTMLDivElement.dispatch (node_modules\jquery\dist\jquery.js:5429:1)
    at HTMLDivElement.$event.dispatch (node_modules\slickgrid\lib\jquery.event.drag-2.3.0.js:387:1)
    at HTMLDivElement.push.15694.$event.dispatch (jquery.event.drag-2.3.0.js:387:1)
    at HTMLDivElement.elemData.handle (node_modules\jquery\dist\jquery.js:5233:1)

core.js:6479 ERROR TypeError: _a.multipleSelect is not a function
    at SingleSelectEditor.isValueChanged (selectEditor.js:401:1)
    at Object.commitCurrentEdit (slick.grid.js:5841:27)
    at EditorLock.commitCurrentEdit (slick.core.js:439:1)
    at HTMLDivElement.handleClick (slick.grid.js:4702:60)
    at HTMLDivElement.dispatch (node_modules\jquery\dist\jquery.js:5429:1)
    at HTMLDivElement.$event.dispatch (node_modules\slickgrid\lib\jquery.event.drag-2.3.0.js:387:1)
    at HTMLDivElement.push.15694.$event.dispatch (jquery.event.drag-2.3.0.js:387:1)
    at HTMLDivElement.elemData.handle (node_modules\jquery\dist\jquery.js:5233:1)
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28659:1)
```
### Possible Solution

I am not finding any alternative to fix this issue.

### Code Sample

**package.json**
`    "angular-slickgrid": "^4.1.0",`

**angular.json**
```
            "scripts": [
              "node_modules/jquery/dist/jquery.js",
              "node_modules/jquery-ui-dist/jquery-ui.min.js",
              "node_modules/slickgrid/lib/jquery.event.drag-2.3.0.js",
              "node_modules/bootstrap/dist/js/bootstrap.js",
              "node_modules/multiple-select-modified/src/multiple-select.js"
            ],
```
**editorObject for the Column Definition**

```
 editor: {
            model: Editors.singleSelect,
          collection: [
            {
              'value': 'APPROVED',
              'label': 'APPROVED'
            },
            {
              'value': 'REJECTED',
              'label': 'REJECTED'
            }
          ]
          },

```

@ghiscoding  Thanks for really amazing work, Please guide me solve this issue.

**Comment by ghiscoding** [comment]
Sorry but I can't help you without a way to replicate, the `onCellChange` is working fine in the demo, so the problem is most probably on your side. I would suggest to clone the Angular-Slickgrid-Demo and to try to replicate the issue directly on that project, so far I see no issue on my side, below is the proof 

![AUYWSZ48KL](https://user-images.githubusercontent.com/643976/149588960-cf8b53d0-55b6-4817-99aa-abeea5640c64.gif)

**Comment by allabouttech0803** [comment]
@ghiscoding Okay sure, I will try to debug and replicate and update this post, if I find root cause. Please close the bug for now.  Thanks again !!

**Comment by mvgadagi** [comment]
@ghiscoding Okay sure, I will try to debug and replicate and update this post, if I find root cause. Please close the bug for now. Thanks again !!

**Comment by mvgadagi** [comment]
@ghiscoding, I could not reproduce this demo repo, so for now, I found an alternative as we are not using the advanced feature in SingleSelect or MultiSelect, for some reason in my repo I have an issue with using  `"node_modules/multiple-select-modified/src/multiple-select.js"` so using the base multiple-select library.

**angular.json**
styles section
`"node_modules/multiple-select/dist/multiple-select.css",`
**scripts section**
`"node_modules/multiple-select/src/multiple-select.js"`

**styles.css**
```
.ms-drop {
  width: 200px!important;
  min-width: 200px!important;
}
```
