### ISSUE TITLE
ERROR TypeError: Cannot set properties of undefined (setting 'translater')

### ISSUE THREAD

**Issue by twalker1998** [ghiscoding/Angular-Slickgrid#910]
### Describe the bug

Receiving this error message when initializing Slickgrid components.

```
ERROR TypeError: Cannot set properties of undefined (setting 'translater')
    at AngularSlickgridComponent.initialization (angular-slickgrid.mjs:1179:9)
    at AngularSlickgridComponent.ngAfterViewInit (angular-slickgrid.mjs:1076:14)
    at callHook (core.mjs:2551:1)
    at callHooks (core.mjs:2520:1)
    at executeInitAndCheckHooks (core.mjs:2471:1)
    at refreshView (core.mjs:9566:1)
    at refreshEmbeddedViews (core.mjs:10646:1)
    at refreshView (core.mjs:9519:1)
    at refreshEmbeddedViews (core.mjs:10646:1)
    at refreshView (core.mjs:9519:1)
```

I have ensured `@ngx-translate/core` is in my dependency list.

### Reproduction

Typescript code:

```ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { KeyValue } from '@angular/common';
import { Column, GridOption } from 'angular-slickgrid';
import { Subscription } from 'rxjs';

export type OccurrenceResult = {
  acode: string;
  county: string;
  recordedby: string;
  eventdate: string;
  locality: string;
  gid: number;
  id: number;
}

@Component({
  selector: 'occurrence-results',
  templateUrl: './results.component.html',
  styleUrls: ['./results.component.css']
})
export class ResultsComponent implements OnDestroy, OnInit {
  originalOrder = (a: KeyValue<string, OccurrenceResult[]>, b: KeyValue<string, OccurrenceResult[]>): number => {
    return 0;
  }

  private subscription: Subscription;

  results: Map<string, Array<OccurrenceResult>>;
  page: number;
  pageSize: number;

  columnDefinitions: Array<Column>;
  gridOptions: GridOption;

  constructor(private route: ActivatedRoute, private router: Router) {
    this.subscription = new Subscription();
    this.results = new Map<string, Array<OccurrenceResult>>();
    this.page = 1;
    this.pageSize = 15;

    this.columnDefinitions = [];
    this.gridOptions = {};
  }

  ngOnInit(): void {
    this.subscription.add(
      // These results are gathered from an API endpoint called from a resolver service. I have also tried manually setting
      // test data in this component to eliminate issues with the API and resolver, and still no dice.
      this.route.snapshot.data.results.subscribe((results: Map<string, Array<OccurrenceResult>>) => {
        if (results) {
          this.results = results;
          this.results.forEach((value: Array<OccurrenceResult>) => {
            value.forEach((occurrence: OccurrenceResult) => occurrence.id = occurrence.gid);
          });
        }
      })
    );

    this.columnDefinitions = [
      { id: 'eventdate', name: 'Event Date', field: 'eventdate', filterable: true, sortable: true },
      { id: 'recordedby', name: 'Recorded By', field: 'recordedby', filterable: true, sortable: true },
      { id: 'county', name: 'County', field: 'county', filterable: true, sortable: true },
      { id: 'locality', name: 'Locality', field: 'locality', filterable: true, sortable: true },
      { id: 'gid', name: 'Gid', field: 'gid', filterable: true, sortable: true }
    ];

    this.gridOptions = {
      autoTooltipOptions: {
        enableForCells: true,
        enableForHeaderCells: false,
        maxToolTipLength: 1000
      },
      editable: false,
      enableAutoResize: true,
      enableAutoSizeColumns: true,
      enableCellNavigation: true,
      enableExcelExport: false,
      enableExport: false,
      enableFiltering: true,
      enablePagination: true,
      enableSorting: true,
      enableTextExport: false,
      forceFitColumns: true,
      gridMenu: {
        hideClearFrozenColumnsCommand: true,
        hideForceFitButton: true
      },
      gridWidth: 600,
      multiColumnSort: true
    };
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe(); 
  }

  openRecord(target: any): void {
    const gid = target.parentElement.children[4].innerText;
    // TODO: navigate to proper route
    // this.router.navigate();
  }
}
```

Template code:

```html
<div *ngIf="results.size > 0" id="results">
  <div id="pagination" class="left">
    <ngb-pagination [(page)]="page" [pageSize]="pageSize" [collectionSize]="results.size" [boundaryLinks]="true"></ngb-pagination>
  </div>
  <mat-accordion>
    <div *ngFor="let result of results | keyvalue: originalOrder | slice: (page - 1) * pageSize : (page - 1) * pageSize + pageSize">
      <mat-expansion-panel>
        <mat-expansion-panel-header class="right-aligned-header">
          <mat-panel-title>{{ result.key }}</mat-panel-title>
          <mat-panel-description>{{ result.value.length }} occurrences found</mat-panel-description>
        </mat-expansion-panel-header>
        <div class="table-container mat-elevation-z8">
          <angular-slickgrid class="grid" [gridId]="'test' + 'Grid'"
            [columnDefinitions]="columnDefinitions"
            [dataset]="result.value"
            (sgOnClick)="openRecord($any($event).detail.eventData.target)">
          </angular-slickgrid>
        </div>
      </mat-expansion-panel>
    </div>
  </mat-accordion>
  <div id="pagination-bottom" class="left">
    <ngb-pagination [(page)]="page" [pageSize]="pageSize" [collectionSize]="results.size" [boundaryLinks]="true"></ngb-pagination>
  </div>
</div>
<div *ngIf="results.size === 0">
    <img class="no-results" src="assets/no-results.png" />
    <h3 style="color: #548235;">Query returned no results.</h3>
</div>
```

### Environment Info

```shell
@angular/core 13.3.8
@angular/material 13.3.7
@ng-bootstrap/ng-bootstrap 12.1.1
@ngx-translate/core 14.0.0
angular-slickgrid 4.1.4
bootstrap 5.1.3
typescript 4.6.4

Browsers: Chrome, Firefox, Safari
OS: Mac OS X 12.0.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DiegoTrapiello** [comment]
I recall having a similar issue. In my gridOptions i have { enableTranslate: true}, maybe try with that?

**Comment by twalker1998** [comment]
if `[gridOptions]` is in fact a required parameter to initialize the slickgrid, shouldn't there be some sort of validation done to ensure it exists there? if not exists, throw error
